[package]
name = "pens"
version = "0.1.0"
authors = ["Bill <me@bl-rd.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
